version: '3'

services:
  app:
    container_name: blogISA
    restart: unless-stopped
    build: ./docker
    image: blog-dev
    volumes:
      - ${PWD}/www:/var/www
    ports:
      - 80:80
    networks:
      - blogISA
    env_file:
      - .env

  mysql:
    container_name: blogISA.mysql
    restart: unless-stopped
    image: mariadb
    networks:
      - blogISA
    env_file:
      - .env

networks:
  blogISA:
    driver: bridge

