version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: ./docker
    image: blog-dev
    volumes:
      - ${PWD}/www:/var/www
    ports:
      - ${CONTAINER_PORT}:80
    networks:
      - blogISA
    env_file:
      - .env

  mysql:
    container_name: ${CONTAINER_MYSQL}
    restart: unless-stopped
    image: mariadb
    expose:
    - "${SQL_INTERNAL_PORT}"
    ports:
      - ${SQL_CLIENT_PORT}:${SQL_INTERNAL_PORT}
    networks:
      - blogISA
    env_file:
      - .env

networks:
  blogISA:
    driver: bridge

